name: Tesing

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main


jobs:
  build:
    runs-on: ubuntu_latest

    steps:
      - name: Check
        uses: actions/checkout@v2
      - name: Set up
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: webtest-master
        run: mvn clean package -DskipTests

      - name: Run Tests
        working-directory: webtest-master
        run: mvn test
  
